// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0CRXsJob3G1CsekML4PO5zytqRZmKvA',
    appId: '1:1077071069798:web:96dc2bcf3598627c72e3a7',
    messagingSenderId: '1077071069798',
    projectId: 'access-link-005',
    authDomain: 'access-link-005.firebaseapp.com',
    storageBucket: 'access-link-005.firebasestorage.app',
    measurementId: 'G-5JJ1YQYSXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSC84Md48hsgisOcsyWUXOTpHa-oblnI',
    appId: '1:1077071069798:android:12ee750c30d0022372e3a7',
    messagingSenderId: '1077071069798',
    projectId: 'access-link-005',
    storageBucket: 'access-link-005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JLiI2HmdW8kWNjKwrXGLup4Fc3-9jfQ',
    appId: '1:1077071069798:ios:a35f342199faf03372e3a7',
    messagingSenderId: '1077071069798',
    projectId: 'access-link-005',
    storageBucket: 'access-link-005.firebasestorage.app',
    iosBundleId: 'com.example.accesslink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JLiI2HmdW8kWNjKwrXGLup4Fc3-9jfQ',
    appId: '1:1077071069798:ios:a35f342199faf03372e3a7',
    messagingSenderId: '1077071069798',
    projectId: 'access-link-005',
    storageBucket: 'access-link-005.firebasestorage.app',
    iosBundleId: 'com.example.accesslink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO0CRXsJob3G1CsekML4PO5zytqRZmKvA',
    appId: '1:1077071069798:web:24ce96a5cc14550572e3a7',
    messagingSenderId: '1077071069798',
    projectId: 'access-link-005',
    authDomain: 'access-link-005.firebaseapp.com',
    storageBucket: 'access-link-005.firebasestorage.app',
    measurementId: 'G-MLPWTPTGRJ',
  );
}
